import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { atomic, database, getRecord, putRecord, enqueue, claimJob, finishJob, pageRecords } from '../lib/storage';
import { createReport, saveDraft, submitReport, getReport } from '../lib/serverStore';
import { ensurePdf, readPdf } from '../lib/pdfArtifacts';
import { runOneJob } from '../lib/reportWorker';
import type { Report } from '../lib/types';

test('transactional report receipt, immutable PDF reuse, and recoverable jobs',async () => {
  const root = mkdtempSync(join(tmpdir(),'relay-store-test-'));
  process.env.RELAY_DATA_ROOT = root;
  try {
    assert.throws(() => atomic(() => { putRecord('test',{id:'rolled-back'}); throw new Error('rollback'); }));
    assert.equal(getRecord('test','rolled-back'),undefined);
    const draft = createReport('proj-011lme','Test Engineer');
    const next: Report = { ...draft, observations:[{id:'obs-1',type:'update',location:'Site',whatHappened:'Work progressing',actionNeeded:'',owner:'',photos:[]}] };
    const requestId = crypto.randomUUID();
    const saved = saveDraft(draft.id,next,draft.version,requestId);
    assert.equal(saved.ok,true);
    const replayed = saveDraft(draft.id,next,draft.version,requestId);
    assert.deepEqual(replayed,saved,'Lost save responses replay without another version increment');
    assert.equal(saveDraft(draft.id,{...next,observations:[]},draft.version,requestId).ok,false,'Request IDs cannot change payload');
    assert.equal(saveDraft(draft.id,next,draft.version).ok,false,'Stale versions cannot overwrite');
    const receipt = await submitReport(draft.id,undefined,saved.value.version);
    assert.equal(receipt.ok,true);
    assert.equal(receipt.value.delivery,'pending');
    assert.equal(getRecord<Report>('snapshots',draft.id)?.observations[0]?.whatHappened,'Work progressing');
    assert.equal(saveDraft(draft.id,next,saved.value.version).ok,false,'Submission is immutable');
    assert.equal((await submitReport(draft.id,undefined,saved.value.version)).ok,true,'Lost receipts are safe to retry');
    assert.equal(database().prepare("SELECT count(*) AS n FROM jobs WHERE kind='pdf'").get()?.n,1);
    const page = pageRecords<any>('reports',draft.projectId);
    assert.equal(page.items[0].observationCount,1);
    assert.equal(page.items[0].observations,undefined);
    let renders = 0;
    const render = async () => { renders++; await new Promise(r => setTimeout(r,20)); return Buffer.from('%PDF-test'); };
    const [first,second] = await Promise.all([ensurePdf(receipt.value,render),ensurePdf(receipt.value,render)]);
    assert.deepEqual(first,second);
    assert.equal(renders,1,'Concurrent requests coalesce');
    assert.deepEqual(await readPdf(receipt.value),first);
    assert.deepEqual(await ensurePdf(receipt.value,render),first);
    assert.equal(renders,1,'Downloads and retries reuse disk artifact');
    assert.equal(await runOneJob(),true);
    assert.equal(getReport(draft.id)?.delivery,'rendered');
    assert.equal(await runOneJob(),true);
    assert.equal(getReport(draft.id)?.delivery,'outbox','Local mail is never reported as sent');
    assert.equal(await runOneJob(),false);
    const realDraft = createReport(draft.projectId,draft.author);
    const realSaved = saveDraft(realDraft.id,{...next,id:realDraft.id},realDraft.version);
    assert.equal(realSaved.ok,true);
    const realReceipt = await submitReport(realDraft.id,undefined,realSaved.value.version);
    assert.equal(realReceipt.ok,true);
    assert.equal(await runOneJob(),true);
    const realPdf = await readPdf(realReceipt.value);
    assert.ok(realPdf && realPdf.length > 1000,'Worker renders a real document');
    assert.equal(realPdf.subarray(0,5).toString(),'%PDF-');
    assert.equal(await runOneJob(),true);
    assert.equal(getReport(realDraft.id)?.delivery,'outbox');
    enqueue('lease-test','test',{});
    const firstLease = claimJob()!;
    assert.equal(claimJob(),undefined,'Active job cannot be claimed twice');
    database().prepare('UPDATE jobs SET available=0 WHERE id=?').run(firstLease.id);
    const recovered = claimJob()!;
    finishJob(firstLease);
    assert.equal(database().prepare('SELECT status FROM jobs WHERE id=?').get(firstLease.id)?.status,'working','Old lease cannot complete recovered work');
    finishJob(recovered);
  } finally {
    database().close();
    delete process.env.RELAY_DATA_ROOT;
    rmSync(root,{recursive:true,force:true});
  }
});
