/**
 * Branded identifiers.
 *
 * Every internal identity is a UUID generated by the application. Human-facing
 * report numbers are assigned centrally and are never used as retry identity
 * (blueprint 0.7). Branding stops a project id being passed where a visit id
 * belongs, which is otherwise indistinguishable to the compiler.
 */

declare const brand: unique symbol;

type Branded<T, B extends string> = T & { readonly [brand]: B };

export type ClientId = Branded<string, "ClientId">;
export type ProjectId = Branded<string, "ProjectId">;
export type VisitId = Branded<string, "VisitId">;
export type ReportId = Branded<string, "ReportId">;
export type ReportRevisionId = Branded<string, "ReportRevisionId">;
export type ObservationId = Branded<string, "ObservationId">;
export type IssueId = Branded<string, "IssueId">;
export type MediaId = Branded<string, "MediaId">;
export type PrincipalId = Branded<string, "PrincipalId">;
export type TemplateVersionId = Branded<string, "TemplateVersionId">;
export type JobId = Branded<string, "JobId">;

/** A client-generated operation id, used as the idempotency key on commands. */
export type ClientOperationId = Branded<string, "ClientOperationId">;

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isUuid(value: string): boolean {
  return UUID_PATTERN.test(value);
}

/** Narrow an untrusted string to a branded id. Throws rather than returning a lie. */
export function asId<T extends string>(value: string, kind: string): Branded<string, T> {
  if (!isUuid(value)) {
    throw new TypeError(`Expected ${kind} to be a UUID, received "${value}"`);
  }
  return value as Branded<string, T>;
}
