import { renderReportPdf } from "@relay/documents";
import { archiveFileName, sanitiseFileName } from "@relay/contracts";
import { alreadyDelivered, resolveRecipients, type IssueRecord } from "@relay/platform";

import { FIXTURE_PROJECTS, OBSERVATION_TYPES } from "../fixtures";
import { resolveTransport } from "./transport";
import type { Report } from "../types";

/**
 * Send a submitted report to the people who need it.
 *
 * Runs on submission rather than after review. Review was made optional
 * because the office is small and a control nobody has capacity to operate is
 * worse than none: reports either pile up unsent or get rubber-stamped, and
 * the second is worse because it looks like review happened.
 *
 * What makes that safe is who this goes to. The project manager is Leodis, so
 * this is internal distribution, and the manager receiving it is itself the
 * check. Sending outside Leodis is a separate act with its own gate — that is
 * where an unsupported statement on Leodis letterhead becomes a commercial
 * problem, and where Appendix C's corrections earn their keep.
 *
 * Filing happens before sending, so what a recipient holds is the same artefact
 * the archive does.
 */

export interface IssueOutcome {
  records: IssueRecord[];
  /** People who should have received it but have no address on file. */
  unaddressed: readonly string[];
  transport: "graph" | "outbox";
  /** Where a locally written message landed, for the interface to point at. */
  location?: string;
}

function bodyFor(report: Report, projectName: string): string {
  const defects = report.observations.filter(
    (o) => o.type === "defect" || o.type === "access",
  ).length;

  return [
    `${projectName}`,
    `Report ${report.reference} — visit ${report.visitDate}`,
    ``,
    `${report.author} has submitted a site report with ${report.observations.length} update${
      report.observations.length === 1 ? "" : "s"
    }${defects > 0 ? `, ${defects} of which raised an issue` : ""}.`,
    ``,
    `The report is attached. Outstanding issues are tracked in Relay.`,
    ``,
    `This message was generated by Relay. Do not reply to it.`,
  ].join("\n");
}

export async function issueReport(
  report: Report,
  existing: readonly IssueRecord[],
): Promise<IssueOutcome> {
  const project = FIXTURE_PROJECTS.find((p) => p.id === report.projectId);

  const { send, unaddressed } = resolveRecipients([
    {
      name: project?.projectManager ?? "",
      address: project?.projectManagerEmail ?? "",
      role: "project_manager",
    },
  ]);

  const { transport, missing } = resolveTransport();
  const records: IssueRecord[] = [];

  if (send.length === 0) {
    return { records, unaddressed, transport: transport.kind, ...(missing.length ? {} : {}) };
  }

  const pdf = await renderReportPdf({
    reference: report.reference,
    projectName: project?.projectName ?? report.projectId,
    projectNumber: project?.projectNumber ?? "",
    clientName: project?.clientName ?? "",
    clientAccountNumber: project?.clientAccountNumber ?? "",
    visitDate: report.visitDate,
    author: report.author,
    revision: report.revision,
    approved: report.review === "approved",
    observations: report.observations.map((o) => {
      const kind = OBSERVATION_TYPES.find((t) => t.value === o.type);
      return {
        id: o.id,
        typeLabel: kind?.label ?? o.type,
        tone: kind?.tone ?? "neutral",
        location: o.location,
        whatHappened: o.whatHappened,
        actionNeeded: o.actionNeeded,
        owner: o.owner,
        photos: o.photos,
      };
    }),
    ...(report.signature ? { signature: report.signature } : {}),
  });

  const fileName = archiveFileName({
    projectNumber: project?.projectNumber ?? "UNKNOWN",
    reportNumber: sanitiseFileName(report.reference),
    revision: report.revision,
    visitDate: report.visitDate,
  });

  const revisionId = report.id as never;

  for (const recipient of send) {
    // A retry after a lost response finds the existing record rather than
    // sending a second copy.
    if (alreadyDelivered(existing, revisionId, "email", recipient.address)) continue;

    const base = {
      revisionId,
      revision: report.revision,
      method: "email" as const,
      recipient,
      at: new Date().toISOString(),
    };

    try {
      await transport.send({
        to: recipient,
        subject: `${report.reference} — ${project?.projectName ?? "Site report"}`,
        body: bodyFor(report, project?.projectName ?? report.projectId),
        attachment: { fileName, bytes: pdf },
      });
      records.push(base);
    } catch (error) {
      // The attempt is recorded either way. A delivery that failed silently is
      // indistinguishable from one that never happened.
      records.push({
        ...base,
        failure: error instanceof Error ? error.message : "Delivery failed.",
      });
    }
  }

  return {
    records,
    unaddressed,
    transport: transport.kind,
    ...(transport.lastLocation ? { location: transport.lastLocation } : {}),
  };
}
